export {DoorIcon} from "./DoorIcon";
export {MedalIcon} from "./MedalIcon";
export {CalendarIcon} from './CalendarIcon';
export {PinIcon} from "./PinIcon";
export {LanguageIcon} from "./LanguageIcon";
export {BusinessIcon} from "./BusinessIcon";
export {ReviewsNumberIcon} from "./ReviewsNumberIcon";
export {VerifiedIcon} from "./VerifiedIcon";
export {RoleIcon} from "./RoleIcon";