services:
  postgres:
    image: postgres:13
    container_name: web-circle-pg  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  
    volumes:
      - web_circle_pg_data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: web-circle-pgadmin  
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"  
    volumes:
      - web_circle_pgadmin_data:/var/lib/pgadmin  

volumes:
  web_circle_pg_data:  
  web_circle_pgadmin_data: