-- CreateTable
CREATE TABLE "Place" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "price" TEXT NOT NULL,
    "accommodation" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "guests" INTEGER NOT NULL,
    "bedrooms" INTEGER NOT NULL,
    "beds" INTEGER NOT NULL,
    "baths" INTEGER NOT NULL,
    "starGrade" DOUBLE PRECISION NOT NULL,
    "reviewsCount" INTEGER NOT NULL,
    "highlightCheckIn" TEXT,
    "highlightAward" TEXT,
    "highlightWifi" TEXT,
    "highlightCancellation" TEXT,
    "amenitiesKitchen" BOOLEAN,
    "amenitiesWorkspace" BOOLEAN,
    "amenitiesSauna" BOOLEAN,
    "amenitiesBalcony" BOOLEAN,
    "amenitiesFireplace" BOOLEAN,
    "amenitiesWifi" BOOLEAN,
    "amenitiesParking" BOOLEAN,
    "amenitiesPets" BOOLEAN,
    "amenitiesBackyard" BOOLEAN,
    "amenitiesFirepit" BOOLEAN,
    "reviewSummaryTotalAvgRating" DOUBLE PRECISION NOT NULL,
    "reviewSummaryTotalReviewsCount" INTEGER NOT NULL,
    "cleanlinessAvgRating" DOUBLE PRECISION NOT NULL,
    "accuracyAvgRating" DOUBLE PRECISION NOT NULL,
    "checkInAvgRating" DOUBLE PRECISION NOT NULL,
    "communicationAvgRating" DOUBLE PRECISION NOT NULL,
    "locationAvgRating" DOUBLE PRECISION NOT NULL,
    "valueAvgRating" DOUBLE PRECISION NOT NULL,
    "starTotalFiveStar" INTEGER NOT NULL,
    "starTotalFourStar" INTEGER NOT NULL,
    "starTotalThreeStar" INTEGER NOT NULL,
    "starTotalTwoStar" INTEGER NOT NULL,
    "starTotalOneStar" INTEGER NOT NULL,
    "lon" DOUBLE PRECISION NOT NULL,
    "lat" DOUBLE PRECISION NOT NULL,
    "mapAddress" TEXT NOT NULL,
    "mapAddressDescription" TEXT NOT NULL,
    "hostName" TEXT NOT NULL,
    "hostingDuration" INTEGER NOT NULL,
    "role" TEXT NOT NULL,
    "hostProfilePicUrl" TEXT NOT NULL,
    "descriptionPlace" TEXT NOT NULL,
    "descriptionSpace" TEXT NOT NULL,
    "guestAccess" TEXT NOT NULL,
    "otherThings" TEXT NOT NULL,

    CONSTRAINT "Place_pkey" PRIMARY KEY ("id")
);
