-- CreateEnum
CREATE TYPE "Category" AS ENUM ('BEACHFRONT', 'LUXE', 'CABINS', 'CASTLES', 'BEACH_HOUSES', 'CHALETS', 'TINY_HOMES', 'RIVERSIDE_CABINS', 'LUXURY_VILLAS', 'AMAZING_POOLS', 'CAMPING', 'ARCTIC', 'CARAVANS', 'TREE_HOUSES', 'FISHING_BOATS', 'SAILBOATS');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "category" "Category"[];
